### ISSUE TITLE
SI41XX_SYNTH Code Upgrade for Pins

### ISSUE THREAD

**Issue by evmastro** [oresat/oresat-firmware#14]
Combine STM32F4 output pins for 4-pin header
  * Group together the pins usage on the M4 board to make sense going forward. Since bit banging is used, not a special pin function, there should be no conflict.
  * Should choose choose what pins are going to be used on the actual C3_Dev_sat board.

**Comment by heliochronix** [comment]
Pins chosen/allocated for SI41XX_SYNTH control on C3 board
