### ISSUE TITLE
STM32F091 DAC Control

### ISSUE THREAD

**Issue by heliochronix** [oresat/oresat-firmware#19]
Configuring and controlling the DAC on the STM32F091 for use by the solar panels to control the I_Adj pin for maximum power point tracking. Preferably implemented in such a way that giving a voltage in milli- or micro-volts (whatever is needed for maximum precision with fixed point values).

**Comment by oliver-rew** [comment]
I figured out the DAC and @Code1983 incorporated it into his solar branch, I am closing this issue

**Comment by heliochronix** [comment]
Merged into master
