### ISSUE TITLE
Change MCU internal sensors API to continuous sample with callback

### ISSUE THREAD

**Issue by heliochronix** [oresat/oresat-firmware#36]
MCU sensors currently require a manual trigger via `sensors_trig()`. Reconfigure them to continuously sample and invoke a callback to log data. Set and forget.

**Comment by ThirteenFish** [comment]
As far as I can tell this (the continuous sampling) was resolved in 51275171 and 37a63659. However 37a63659 disabled actually starting the sampling and it's never been re-enabled since. See #100 for more.
