### ISSUE TITLE
Make and merge F0 bootloader when building bootloader enabled F0 application

### ISSUE THREAD

**Issue by heliochronix** [oresat/oresat-firmware#46]
When an F0 application has the bootloader enabled, build the bootloader code using the parent applications configurations and write it in addition to the application code.

**Comment by ThirteenFish** [comment]
This has been implemented, with the latest significant commit being ccb5b04b. Relevant F0 projects automatically pull in the bootloader during build using the [`f0_pack_image.py`](https://github.com/oresat/oresat-firmware/blob/master/toolchain/f0_pack_image.py) script.
