### ISSUE TITLE
C3 firmware recovery system (choosing firmware banks)

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-firmware#54]
After discussion today, we decided that we're gong to try to leave Bank 0 the way it is, forever, and leave that as the "Bank of first and last resort". We'll only update Bank 1 with new firmware.

We need code that runs in Bank 1 that chooses to switch back to Bank 0 if:

- We get too many reboots due to system lockups
- We lose communication with the ground
- Other reasons?

This code would switch back to Bank 0 which we know vaguely works and can do communication and firmware updates.

**Comment by ryanpdx** [comment]
No longer relevant
