### ISSUE TITLE
C3 eMMC file downlink

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-firmware#56]
The C3 needs to be able to download files to the ground from its eMMC. For example, to download its log. We need three bits of functionality:

- EDL ls (transmit the lfs fs ls command to the ground - maybe traverse the entire file system tree? Or we don't use directories?)
- EDL uplink requesting a file (with file path)
- EDL segmented downlink with the file (send it like we upload messages)

**Comment by ryanpdx** [comment]
No longer relevant
