### ISSUE TITLE
C3 CAN bootloader support for F0s

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-firmware#76]
All F0s have a CAN bootloader built into them that talks the STM32 CAN bootloader protocol. It's a software implementation of what is usually in the hardware for CAN bootloaders in STM32s. However, our F091s don't have that. So we did in software. This has been tested by Dave; now we need the ability to write to the firmware over CAN from a file on the eMMC.

**Comment by ryanpdx** [comment]
No longer relevant to this repo
