### ISSUE TITLE
Resolve memory issues

### ISSUE THREAD

**Issue by MaxMSchweitzer** [oresat/oresat-firmware#9]
In the current state, we are running critical on memory. We need to figure out how we can save more space (reducing thread sizes? These are getting about as small as they can be already), or if we need to upgrade.

**Comment by heliochronix** [comment]
ChibiOS debugging options take a lot of space. Disabling ChibiOS debugging options slims down builds considerably, and can be activated individually to test things as needed. New F0 app_template start with ChibiOS debugging options disabled, and L4 has plenty of room even with them turned on.
